---
- hosts: all
  name: Setup base image
  become: yes
  become_method: sudo
  roles:
    #  Temporarily removing this due to Amazon Linux 2 vs 2023
    #- automated_security_updates
    - persist_journald
